### ISSUE TITLE
Bootstrap to CSS Grid

### ISSUE THREAD

**Issue by tehhowch** [DevJackSmith/mh-helper-extension#60]
https://hacks.mozilla.org/2017/04/replace-bootstrap-layouts-with-css-grid/

May be worthwhile. Are there any other uses we have for bootstrap in the options and popup pages?

**Comment by DevJackSmith** [comment]
what are we trying to fix here? or what feature to add?

If it works and it's not broken, don't fix it. -- My mechanic.

I understand that we all want new and shiny. But old and familiar is much easier to maintain. Upgrading for the sake of upgrading is bad. Unless we all learn how to use the new way, this will be hard to troubleshoot.

Now that I've gotten that out: we use bootstrap for easy styling on maps, and every single page except one or two. Not only grid, but default fonts, default styling for datatables, buttons, checkboxes, input fields, alignment, spacing, etc. Bootstrap is also compatible with all browsers, i only see article talking about Firefox. While I support FF moving to better ways (less buggy, better names, etc as the article claims), i don't see a need for it at this time.

Thanks for bringing it up though.
